repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      # -   id: check-yaml
      #     verbose: true
      - id: end-of-file-fixer
        verbose: true
      - id: trailing-whitespace
        verbose: true
      - id: check-json
        verbose: true
      - id: check-merge-conflict
        verbose: true
      - id: flake8
        verbose: true
    # -   id: name-tests-test
    #     verbose: true
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        verbose: true
default_language_version:
  python: python3.6
