version: 0.2
phases:
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - $(aws ecr get-login --no-include-email --region us-east-2)
    build:
      commands:
        - echo Build started on `date`
        - echo \"Building the Training Docker image...\"
        - cd $CODEBUILD_SRC_DIR
        - REPO=168996373046.dkr.ecr.us-east-2.amazonaws.com/cloud-dev
        - IMAGE_TAG=latest
        - apt-get update
        - apt install docker.io
        - systemctl start docker
        - systemctl enable docker
        - docker --version
        - ls
        - docker build -t cloud-dev .
        - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPO:$IMAGE_TAG
        - echo \"Pushing the Docker image...\"
        - docker push $REPO:$IMAGE_TAG
    post_build:
        commands:
        - echo Build completed on `date`
