# version: 0.2
# phases:
#     pre_build:
#       commands:
#         - echo Logging in to Amazon ECR...
#         - $(aws ecr get-login --no-include-email --region us-east-2)
#     build:
#       commands:
#         - echo Build started on `date`
#         - echo \"Building the Training Docker image...\"
#         - cd $CODEBUILD_SRC_DIR
#         - REPO=168996373046.dkr.ecr.us-east-2.amazonaws.com/cloud-dev
#         - IMAGE_TAG=latest
#         - apt-get update
#         - apt -y install docker.io
#         - docker --version
#         - ls
#         - dockerd

#         # - docker build -t cloud-dev .
#         # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPO:$IMAGE_TAG
#         # - echo \"Pushing the Docker image...\"
#         # - docker push $REPO:$IMAGE_TAG
#     post_build:
#         commands:
#         - echo Build completed on `date`
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      docker: 18
    commands:
      - rm -rf /var/lib/docker/*
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Entering the install phase.....
      - apt-get update -y
      - apt-get -y install python-pip -y
      - pip install awscli --upgrade --user
      - pip install boto3
      - pip install anchorecli
    pre_build:
      commands:
        - echo Image repository setup started on `date`
        - echo ECR Setup...
        - echo Logging into AWS ECR...
        - $(aws ecr get-login --no-include-email --region us-east-2)
    build:
      commands:
        - echo Deployment started on `date`
